import { isOtsConfigured } from "@/lib/ots-config";
import { computeTravelStats } from "@/lib/ots/travel";
import type { Flight, Train, VisitWithImages } from "@/lib/types/travel";

const CREATED = "2024-06-01T00:00:00Z";

/** Dev-only sample data when OTS credentials are absent (local UI / map checks). */
export function shouldUseTravelDummyData(): boolean {
  if (process.env.NODE_ENV !== "development") return false;
  if (process.env.TRAVEL_DUMMY_DATA === "1") return true;
  return !isOtsConfigured();
}

const dummyVisits: VisitWithImages[] = [
  {
    visit_id: "dummy-visit-xishuangbanna",
    date: "2024-02-10",
    province: "云南",
    city: "景洪",
    attraction: "中科院西双版纳热带植物园",
    type: "景点",
    country: "中国",
    rating: 5,
    highlights: "Local dummy data for map testing.",
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-beihai",
    date: "2024-03-05",
    province: "广西",
    city: "北海",
    attraction: "银滩",
    type: "景点",
    country: "中国",
    rating: 4,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-taipei",
    date: "2024-04-12",
    province: "台湾",
    city: "台北",
    attraction: "国立故宫博物院",
    type: "博物馆",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-shanghai",
    date: "2024-05-01",
    province: "上海",
    city: "上海",
    attraction: "外滩",
    type: "景点",
    country: "中国",
    rating: 4,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-guangzhou",
    date: "2024-05-18",
    province: "广东",
    city: "广州",
    attraction: "陈家祠",
    type: "景点",
    country: "中国",
    rating: 4,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-tokyo",
    date: "2023-11-20",
    province: "",
    city: "东京",
    attraction: "浅草寺",
    type: "景点",
    country: "日本",
    rating: 4,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-harbin",
    date: "2024-01-15",
    province: "黑龙江",
    city: "哈尔滨",
    attraction: "圣索菲亚大教堂",
    type: "景点",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-hailar",
    date: "2024-01-18",
    province: "内蒙古",
    city: "海拉尔",
    attraction: "呼伦贝尔大草原",
    type: "景点",
    country: "中国",
    rating: 5,
    highlights: "Winter grassland.",
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-urumqi",
    date: "2023-09-10",
    province: "新疆",
    city: "乌鲁木齐",
    attraction: "新疆国际大巴扎",
    type: "景点",
    country: "中国",
    rating: 4,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-dunhuang",
    date: "2023-09-14",
    province: "甘肃",
    city: "敦煌",
    attraction: "莫高窟",
    type: "景点",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-lhasa",
    date: "2023-07-22",
    province: "西藏",
    city: "拉萨",
    attraction: "布达拉宫",
    type: "景点",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-xian",
    date: "2023-12-03",
    province: "陕西",
    city: "西安",
    attraction: "兵马俑",
    type: "景点",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-chengdu",
    date: "2023-12-06",
    province: "四川",
    city: "成都",
    attraction: "大熊猫繁育研究基地",
    type: "景点",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
  {
    visit_id: "dummy-visit-beijing",
    date: "2024-06-08",
    province: "北京",
    city: "北京",
    attraction: "故宫博物院",
    type: "博物馆",
    country: "中国",
    rating: 5,
    created_at: CREATED,
    updated_at: CREATED,
    images: [],
  },
];

const dummyFlights: Flight[] = [
  {
    flight_id: "dummy-flight-sh-km",
    flight_date: "2024-05-20",
    airline: "东方航空",
    flight_number: "MU5804",
    departure_city: "上海虹桥",
    departure_time: "08:00",
    arrival_city: "昆明长水",
    arrival_time: "11:20",
    distance_km: 2260,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-xsb-km",
    flight_date: "2024-02-09",
    airline: "东方航空",
    flight_number: "MU5914",
    departure_city: "西双版纳嘎洒",
    arrival_city: "昆明长水",
    distance_km: 390,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-tpe-pvg",
    flight_date: "2024-04-11",
    airline: "南方航空",
    flight_number: "CZ3096",
    departure_city: "中国台北桃园",
    arrival_city: "上海浦东",
    distance_km: 680,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-kwl-tpe",
    flight_date: "2024-03-15",
    airline: "南方航空",
    flight_number: "CZ3019",
    departure_city: "桂林两江",
    arrival_city: "中国台北桃园",
    distance_km: 920,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-bh",
    flight_date: "2024-03-04",
    airline: "东方航空",
    flight_number: "MU6399",
    departure_city: "上海浦东",
    arrival_city: "北海福成",
    distance_km: 1800,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-sy",
    flight_date: "2024-01-08",
    airline: "东方航空",
    flight_number: "MU5468",
    departure_city: "上海浦东",
    arrival_city: "三亚凤凰",
    distance_km: 2050,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-intl",
    flight_date: "2023-11-19",
    airline: "东方航空",
    flight_number: "MU521",
    departure_city: "上海浦东",
    arrival_city: "东京成田",
    distance_km: 1780,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-sh-hrb",
    flight_date: "2024-01-14",
    airline: "南方航空",
    flight_number: "CZ6218",
    departure_city: "上海浦东",
    arrival_city: "哈尔滨太平",
    distance_km: 1680,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-hrb-hld",
    flight_date: "2024-01-17",
    airline: "中国国航",
    flight_number: "CA1247",
    departure_city: "哈尔滨太平",
    arrival_city: "呼伦贝尔海拉尔",
    distance_km: 520,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-sh-urc",
    flight_date: "2023-09-09",
    airline: "东方航空",
    flight_number: "MU5633",
    departure_city: "上海浦东",
    arrival_city: "乌鲁木齐地窝堡",
    distance_km: 3640,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-urc-dnh",
    flight_date: "2023-09-13",
    airline: "南方航空",
    flight_number: "CZ6951",
    departure_city: "乌鲁木齐地窝堡",
    arrival_city: "敦煌莫高",
    distance_km: 980,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-xiy-dnh",
    flight_date: "2023-09-12",
    airline: "东方航空",
    flight_number: "MU2157",
    departure_city: "西安咸阳",
    arrival_city: "敦煌莫高",
    distance_km: 1100,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-ctu-lxa",
    flight_date: "2023-07-21",
    airline: "四川航空",
    flight_number: "3U8693",
    departure_city: "成都双流",
    arrival_city: "拉萨贡嘎",
    distance_km: 1280,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-pek-xiy",
    flight_date: "2023-12-02",
    airline: "中国国航",
    flight_number: "CA1201",
    departure_city: "北京首都",
    arrival_city: "西安咸阳",
    distance_km: 934,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-xiy-ctu",
    flight_date: "2023-12-05",
    airline: "四川航空",
    flight_number: "3U8618",
    departure_city: "西安咸阳",
    arrival_city: "成都双流",
    distance_km: 635,
    status: "completed",
    created_at: CREATED,
  },
  {
    flight_id: "dummy-flight-can-xiy",
    flight_date: "2024-05-17",
    airline: "南方航空",
    flight_number: "CZ3215",
    departure_city: "广州白云",
    arrival_city: "西安咸阳",
    distance_km: 1300,
    status: "completed",
    created_at: CREATED,
  },
];

const dummyTrains: Train[] = [
  {
    train_id: "dummy-train-beihai",
    train_date: "2024-03-05",
    train_type: "动车",
    train_number: "D3926",
    departure_station: "北海",
    departure_time: "09:30",
    arrival_station: "南宁",
    arrival_time: "10:45",
    duration_minutes: 75,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-gz-hk",
    train_date: "2024-05-19",
    train_type: "高铁",
    train_number: "G653",
    departure_station: "广州南",
    departure_time: "14:00",
    arrival_station: "香港西九龙",
    arrival_time: "14:45",
    duration_minutes: 45,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-sh-hz",
    train_date: "2024-05-02",
    train_type: "高铁",
    train_number: "G7311",
    departure_station: "上海虹桥",
    departure_time: "10:00",
    arrival_station: "杭州东",
    arrival_time: "10:45",
    duration_minutes: 45,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-bj-hrb",
    train_date: "2024-01-14",
    train_type: "高铁",
    train_number: "G1201",
    departure_station: "北京",
    departure_time: "08:00",
    arrival_station: "哈尔滨",
    arrival_time: "14:30",
    duration_minutes: 390,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-lz-dnh",
    train_date: "2023-09-13",
    train_type: "动车",
    train_number: "D2749",
    departure_station: "兰州",
    departure_time: "07:30",
    arrival_station: "敦煌",
    arrival_time: "12:15",
    duration_minutes: 285,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-urc-lz",
    train_date: "2023-09-11",
    train_type: "高铁",
    train_number: "G8152",
    departure_station: "乌鲁木齐",
    departure_time: "09:00",
    arrival_station: "兰州",
    arrival_time: "16:40",
    duration_minutes: 460,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-xa-cd",
    train_date: "2023-12-05",
    train_type: "高铁",
    train_number: "D1921",
    departure_station: "西安",
    departure_time: "13:00",
    arrival_station: "成都",
    arrival_time: "16:30",
    duration_minutes: 210,
    status: "completed",
    created_at: CREATED,
  },
  {
    train_id: "dummy-train-gz-wh",
    train_date: "2024-05-16",
    train_type: "高铁",
    train_number: "G1102",
    departure_station: "广州",
    departure_time: "11:00",
    arrival_station: "武汉",
    arrival_time: "15:20",
    duration_minutes: 260,
    status: "completed",
    created_at: CREATED,
  },
];

export function getDummyTravelData() {
  const stats = computeTravelStats(dummyVisits, dummyFlights, dummyTrains);
  return {
    visits: dummyVisits,
    flights: dummyFlights,
    trains: dummyTrains,
    stats,
  };
}
